# Template C++ Application

# This template allows you to validate your C++ application.
# The workflow allows running tests and code linting on the default branch.


image: gcc:10.2


pipelines:
  default:
     - step:
        script:
        - apt-get update && apt-get -y install cmake
        - cd ./Cpp/Learning-Cpp/build/
        - ls
        - cmake ..
        - cmake --build . --target all
